### ISSUE TITLE
problemas

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby#1]
[practica 3 sprint 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby/files/12805300/practica.3.sprint.2.pdf)

**Comment by elisa1223** [comment]
Portada 25%
Procedimiento 22%
Figuras e ilustraciones y fotografías 14%(cuenta con solo 3 imagenes)
Resultados y conclusiones 15%

Calificacion final: 15.2 / 20
Evaluado por el equipo de Elisa Sánchez Coronel.

**Comment by josealfredo79** [comment]
Revisado...
