### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by 00Asaf00** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby#2]
[PDF](https://drive.google.com/file/d/1Ymu_rZ3DdwHAM8wJpk92smA3uJ08lvZV/view?usp=drivesdk)

**Comment by DiegoLV117** [comment]
Portada 25%
Procedimiento 22% 
Figuras e ilustraciones y fotografías 20%
Resultados y conclusiones 20% (Faltaban resultados) 

Calificacion final: 17.4 / 20
Evaluado por el equipo de Elisa Sánchez Coronel.

**Comment by josealfredo79** [comment]
Revisado...
