### ISSUE TITLE
practica

### ISSUE THREAD

**Issue by bibiana-m** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby#3]
[practicas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby/files/12826343/practicas.pdf)

**Comment by elisa1223** [comment]
Portada: 22%
Procedimiento :17%
Figuras e ilustraciones y fotografías 14%(solo cuenta con 3 imagenes)
Resultados y conclusiones 0% (no tiene conclusion ni resultados)

Calificacion final: 10.6 / 20
Evaluado por el equipo de Elisa Sánchez Coronel.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
