### ISSUE TITLE
practica

### ISSUE THREAD

**Issue by Alberto796** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby#4]
[practica 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-club-noobbaby/files/12826785/practica.3.0.pdf)

**Comment by Mari-00** [comment]
Portada: 25%
Procedimiento: 15% (falta de ejercicios y mal resultados)
Figuras: 17% (falta la descripción de imágenes)
Resultados y conclusiones: 20%
Total: 15.4%
Evaluado por Mari Cruz y Anais

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
